// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGameTask.Persistence;

namespace WebGameTask.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210417113122_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebGameTask.Models.GameTask", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Name");

                    b.ToTable("GameTasks");
                });

            modelBuilder.Entity("WebGameTask.Models.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Solutions");
                });
#pragma warning restore 612, 618
        }
    }
}
